typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"
export TERM=xterm-256color
export COLORTERM=truecolor
export PATH=$PATH:~/.platformio/penv/bin
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
alias ff="fastfetch --pipe false"
alias c="clear"
alias python="python3"
alias py="python3"
alias gitsync="{{HOME}}/gitsync.sh"
alias gs="gitsync"
alias ss="open -a ScreenSaverEngine"
alias matlab="/Applications/MATLAB_R2025b.app/bin/matlab -nodisplay"
alias sleep="sudo pmset -a disablesleep 1"
alias wake="sudo pmset -a disablesleep 0"
alias nf="neofetch"
alias e="exit"

eval "$(zoxide init zsh)"

[ -f "{{HOME}}/.ghcup/env" ] && . "{{HOME}}/.ghcup/env"

c && ff

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
alias rf='rm -rf'
